# Generated by Django 4.2.6 on 2024-03-17 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubRoutes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("route_name", models.CharField(max_length=100)),
                ("order", models.IntegerField()),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.location",
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="routes",
            old_name="route_name",
            new_name="route_title",
        ),
        migrations.RemoveField(
            model_name="routes",
            name="location",
        ),
        migrations.RemoveField(
            model_name="routes",
            name="order",
        ),
        migrations.RemoveField(
            model_name="routes",
            name="route",
        ),
        migrations.AddField(
            model_name="routes",
            name="bus_id",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.DeleteModel(
            name="RoutesTitle",
        ),
        migrations.AddField(
            model_name="subroutes",
            name="route",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="api.routes"
            ),
        ),
    ]
