# Generated by Django 5.0.1 on 2024-03-17 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_subroutes_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.location'),
        ),
    ]
